# Site settings
title:       "Explainercast"
description: "A podcast of deep, thorough explanations about physics, engineering, and technology"
podcast_authors: "Shane Swenson and Dave Smith"
baseurl:     ""
url:         "https://explainercast.com"
date_format: "%b %-d, %Y"

# URLs:
hero_image_url:        "https://download.explainercast.com/explainercast-cover-art-500x500.jpg"
podcast_feed_url:      "https://explainercast.com/feed.xml"
podcast_itunes_url:    "https://podcasts.apple.com/us/podcast/explainercast/id1685074583"
podcast_youtube_url:   "https://www.youtube.com/playlist?list=PLjQ0cyFHvP2Sef2MnVngvD5_c9t6UjJ0I"
podcast_spotify_url:   "https://open.spotify.com/show/4pOjU3hW07Oks6bzPGwXvE"
podcast_cover_art_url: "https://download.explainercast.com/explainercast-cover-art.jpg"

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Build settings
markdown:     kramdown
permalink:    "/:year/:month/:day/:title/"
paginate:     100
plugins:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor, ve, scripts, dev.sh, '*auth.json', Gemfile, Gemfile.lock, .editorconfig, '*.rb', Rakefile]
